### ISSUE TITLE
Monitoren projecten NLCS

### ISSUE THREAD

**Issue by ElisabethDeVries** [nl-digigo/NLCS#247]
De volgende ontwikkelprojecten zijn gepland bij NLCS, voor deze projecten moet soms nog een financier gevonden worden:

- [ ] #184 Stedelijk Spoor
- [ ] #201 Netbeheer
- [ ] #204 Constructies
- [ ] #202 RAW
- [ ] #205 3D
- [ ] #207 inmeting 
- [ ] #193 Verkeersborden
- [ ] Monitoren project Implementatieondersteuning Linked Data
- [ ] #138 ISO 19650
- [ ] #214 BGT ontology alignment
- [ ] #187 IMBOR
- [ ] #195 GWSW ontology alignment
- [ ] Monitoren project NL-sfb
- [ ] Monitoren project Onderzoek teken- en modelleringsstandaarden
- [ ] #248
- [ ] Monitoren project NLCS Bomendatabase

De volgende releases zijn gepland op volgorde van release:
- [ ] #213 Release 5.0 linked data
- [ ] Release 5.1
- [ ] Release 5.2 Verkeerslichten
- [ ] Release 5.3 Stedelijk Spoor
- [ ] Release 5.4 Netbeheer
- [ ] Release 5.5 IMBOR
- [ ] Release 5.6 Verkeersborden

- [ ]
